### ISSUE TITLE
Dokumentation Backup

### ISSUE THREAD

**Issue by JudithBre** [digital-peaks/web-aoa#104]
Tasks dazu: https://github.com/digital-peaks/web-aoa/issues/80

**Problemanalyse im Pflichtenheft**
- Backups von wichtigen Benutzerdaten werden regelmäßig durchgeführt und auf ein sicheren Cloud-Storage abgelegt.
- Diese Daten werden für mehrere Tage vorgehalten.

**Comment by nschnierer** [comment]
#116
