### ISSUE TITLE
User-Story "Modell + Trainingsdaten" prüfen

### ISSUE THREAD

**Issue by JudithBre** [digital-peaks/web-aoa#69]
Siehe #31

**Comment by JudithBre** [comment]
Interesting paragraph:

Lastenheft 1.5 Projetct goals
[...]
The system to be developed
combines training, prediction (here LULC classes) and applicability estimation, and
supports two modes of operation:
a) the user submits **a trained model and** selects an **area of interest:** the system
performs the classification and computes the AOA
b) the user submits **a (trained or untrained) model and training data** **and selects an
area of interest:** the system performs the training, the prediction and computes
the AOA
[...]

Vermutlich haben wir daher die folgende User Story abgeleitet:
Als Nutzer*in habe ich die Optionen, ein trainiertes Modell hochzuladen oder ein (trainiertes oder untrainiertes) Modell und Trainingsdaten hochzuladen #31

**Comment by JudithBre** [comment]
@xcomagent95 Ein bereits trainiertes Modell wird vom User hochgeladen. Wenn dann noch zusätzlich weitere Trainingsdaten vom User hochgeladen werden, hat das dann einen Einfluss auf die Berechnungen in R?

**Comment by xcomagent95** [comment]
Nein. Entwerder neu trainieren oder trainiertes benutzen...

**Comment by JudithBre** [comment]
Brauchen wir die Möglichkeit ein untrainiertes Modell hochzuladen? Im Lastenheft wird es auf jeden Fall aufgeführt... Dafür würde ich jetzt denken benötigen wir auch Trainingsdaten, damit es sich am Ende um ein trainiertes Modell handelt.

**Comment by xcomagent95** [comment]
Ich wüsste nicht wie ein "untrainiertes Modell" aussehen sollte. Zudem kann man wie gesagt ein vorhandenes Modell soweit ich weiß nicht mehr verändern sprich zusätzlich Trainieren. Insofern brauchen wir die Möglichkeit nicht.

**Comment by JudithBre** [comment]
Bei dem heutigen Weekly Scrum Meeting fand eine gemeinsamen Absprache über das weitere Vorgehen statt.
Von @JudithBre wird ein Change-Request in die Wege geleitet. 
**Ergebnis: Ein trainiertes Modell** wird hochgeladen **und die AOI** ausgewählt
oder **Trainingsdaten** werden hochgeladen **und die AOI** ausgewählt.

**Comment by JudithBre** [comment]
Das Issue kommt noch in das Review.

**Comment by JudithBre** [comment]
Das Ergebnis wurde von [Edzer Pebesma](https://github.com/edzer/) und [Christian Knoth](https://github.com/DaChro) akzeptiert, siehe #93. Damit ist das Issue abgeschlossen.
