### ISSUE TITLE
Testing fokussieren

### ISSUE THREAD

**Issue by nschnierer** [digital-peaks/web-aoa#78]
* Wie wollen wir Tests implementieren?
* Manuelles Testing?

**Comment by JudithBre** [comment]
Tasks dazu: https://github.com/digital-peaks/web-aoa/issues/80

**Nicht-funktionale Anforderungen aus dem Lastenheft** 
Schulung und Demonstration

und 
**Nichtfunktionale Anforderungen aus dem Pflichtenheft**
Allgemeine Anforderungen im Pflichtenheft

- Der Auftragnehmer stellt ein Testskript oder eine Testsuite zur Verfügung, um den Demoprozess auszuführen und die mit einem einzigen Befehl oder Klick zu validieren. 
(Auf Nachfrage gegenüber [Christian Knoth](https://github.com/DaChro) und [Edzer Pebezma](https://github.com/edzer/) am 26.01.2022 kam die folgende Rückmeldung: 
Die Testsuite soll nicht ins Frontend integriert werden, sondern wird für Einrichtung erwartet.
Die Nutzenden sollen möglichst schnell ein Ergebnis erhalten, sobald etwas läuft.)

**Comment by nschnierer** [comment]
#110
